language: r

apt_packages:
  - seq-gen

r_github_packages:
  - hadley/testthat 
  - jimhester/covr
  - jimhester/lintr

install:
  - wget http://www.mabs.at/ewing/msms/msms3.2rc-b163.jar && sudo mv msms3.2rc-b163.jar /usr/local/bin/msms.jar

after_success:
  - Rscript -e 'library(covr);coveralls()'
  - Rscript -e 'lintr::lint_package()'

notifications:
  email:
    on_success: change
    on_failure: always
