language: c

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_github hadley/testthat 
  - ./travis-tool.sh r_binary_install ape phyclust
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh aptget_install seq-gen
  - wget http://www.mabs.at/ewing/msms/msms3.2rc-b163.jar && sudo mv msms3.2rc-b163.jar /usr/local/bin/msms.jar

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - ./travis-tool.sh r_binary_install igraph stringdist
  - ./travis-tool.sh install_github jimhester/lintr
  - Rscript -e 'lintr::lint_package()'
  - ./travis-tool.sh install_github jimhester/covr
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: always
