language: c

env:
  global:
    - WARNINGS_ARE_ERRORS=1
    - BOOTSTRAP_LATEX="1"
    - R_BUILD_ARGS=" "
    - R_CHECK_ARGS="--as-cran"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh r_binary_install ape abc RcppArmadillo knitr rmarkdown
  - ./travis-tool.sh install_deps
  - ./travis-tool.sh aptget_install seq-gen pandoc pandoc-citeproc
  - mkdir ~/bin
  - wget -P ~/bin/ http://pst-public.s3-website.eu-central-1.amazonaws.com/msms.jar
  - wget -P ~/bin/ http://pst-public.s3-website.eu-central-1.amazonaws.com/OmegaPlus
  - chmod +x ~/bin/*

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

after_success:
  - ./travis-tool.sh r_binary_install igraph stringdist shiny
  - ./travis-tool.sh install_github jimhester/lintr
  - ./travis-tool.sh r_install covr
  - Rscript -e 'lintr::lint_package()'
  - Rscript -e 'library(covr); coveralls()'

notifications:
  email:
    on_success: change
    on_failure: always
